### ISSUE TITLE
Can't find avi file anywhere that was saved after morhphing

### ISSUE THREAD

**Issue by quki** [alyssaq/face_morpher#19]
Can't find avi file anywhere that was saved after morhphing.

I executed below command,

`$python3 facemorpher/morpher.py --images=./test --out_video=test.avi`

and then console shows

```
./test/baby.jpg
./test/adult.jpg
test.avi saved
```

In test directory, It has two face images baby.jpg and adult.jpg
but I cannot find test.avi anywhere.

Is that right way to create avi file??

**Comment by alyssaq** [comment]
Did you manage to locate the test.avi file?

**Comment by quki** [comment]
Yes, I tried to manage location of test.avi file.
like

`$python3 facemorpher/morpher.py --images=./test --out_video=/mypath/test.avi`
