### ISSUE TITLE
Question - running it realtime against a webcam video stream

### ISSUE THREAD

**Issue by aliw77** [alyssaq/face_morpher#2]
Alyssa, do you know what would be the main bottleneck if we were to create a real-time use-case which shows a morphed (50% blended with a reference image)

**Comment by alyssaq** [comment]
It should be possible but i cant say how smooth it'll be to process at 60fps. Face detecting and tracking is pretty good at real-time. Finding face points and morphing would be the additional computation but its not that intensive. The 50% blend is easy for the computer. 

Ill be really interested to see if it works smoothly with a web cam. Let me know if you try it out!

**Comment by aliw77** [comment]
thank you for your response :) Do you know of any library that could do a blend of 3d mesh (if depth data were to come from Kinect).  Please connect w me on aliksg at gmail to discuss offline.  I do not want to pollute the task list to have a one-off discussion (and sorry for already doing that)

**Comment by alyssaq** [comment]
Moving discussion offline
