### ISSUE TITLE
How to place the morphed face back to 1st image?

### ISSUE THREAD

**Issue by lokeshsinhax** [alyssaq/face_morpher#25]
Hi,

Please can you tell me how to place the morphed face back on 1st image?
I am talking about averager.py.
The outcome has to be-
1st image's hair, body etc.,  with the morphed face.
I tried digging into averager.py with no success.

**Comment by shakhyap** [comment]
Yes. Same issue here. +1

the morph is so perfect. well done.

**Comment by shakhyap** [comment]
can u pls tell how to add the morph on a face 1.?

**Comment by singireddysravankumar** [comment]
Hi i am new to python please can you tell me how to morph the images using commands in linux.

thanks in advance

**Comment by alyssaq** [comment]
Ive added a new flag into `averager.py` to overlay the average face unto a supplied face image.
To use: `python averager.py--images=images --destimg=faceimg.jpg --plot`

For example, average of the top 2 images are overlaid on image1. Output on the bottom.
You may have to do more post-processing to blend the edges.
<img width="637" alt="screen shot 2017-09-18 at 8 50 25 pm" src="https://user-images.githubusercontent.com/2819448/30542959-d9d29214-9cb3-11e7-94ab-58d8dd07b2fd.png">

**Comment by lokeshsinhax** [comment]
Thanks it works.
