### ISSUE TITLE
ModuleNotFoundError: No module named 'locator'

### ISSUE THREAD

**Issue by amandawhitney** [alyssaq/face_morpher#28]
I installed all of the dependencies for Python 3.6 but whenever I try to import facemorpher I get this issue:

`ModuleNotFoundError: No module named 'locator'`

I checked the package directory `/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/facemorpher` 

and I can see the files there but Python refuses to find them

`__init__.py	aligner.py	bin		cvver.py	locator.py	plotter.py	warper.py
__pycache__	averager.py	blender.py	data		morpher.py	videoer.py`

any help would be much appreciated. I'm on macOS High Sierra.

**Comment by mkjeong0** [comment]
hi. 
try to find locator.py file and move it to your home directory.

**Comment by alyssaq** [comment]
I just tested and realised that the package on PyPI was out-of-date. I have updated the package and verified that it works on macOS with Python3. Please reinstall facemorpher get the latest facemorpher-3.0.0. Thanks for reporting!

**Comment by mkjeong0** [comment]
Thank you very much sir! It was really helpful for me to learn
face-recognizing. I hope your future always goes well.

Cheers!
Mike, Jeong. from South Korea.

2018-01-09 19:28 GMT+09:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
Cool. Closing this issue. Feel free to open a new one if you run into more issues.
