### ISSUE TITLE
FOURCC problem

### ISSUE THREAD

**Issue by crouti** [alyssaq/face_morpher#4]
Hi!

Wonderfull program : thank you very much !
Anyway, using python 2.7 and OpenCV 2.4 or 3 (tried both), launching command:

```
python facemorpher/morpher.py --src=steph.png --dest=max.png 
```

i get the following error

```
video = videoer.Video(out_video, fps, width, height)
  File "/Users/maxunger/Downloads/facemorpher-1.0.1/facemorpher/videoer.py", line 19, in __init__
    fourcc = cv2.cv.FOURCC('m', 'p', '4', 'v')
AttributeError: 'module' object has no attribute 'cv'
```

Any idea ?
Thank you!

**Comment by alyssaq** [comment]
Hi

Thanks for checking out face_morpher! The program only supports cv2. 

The error is not about fourcc but about cv2.cv.
This is a fairly commonly error that happens with an incomplete install of openCV 2:
<https://www.google.com/search?q=cv+module+in+cv2>

Ive run into this error before and i had to re-install opencv2 to get it cv available in cv2.

**Comment by alyssaq** [comment]
I just realised that you dont even need FOURCC as you're not creating a video.
I've updated the code to not use it unless you specify a --out_video.
Please pull the latest code and try again. You may not have to reinstall openCV :smile:

**Comment by crouti** [comment]
Thank you very much for your quick answer!
I'll try it right now.
I am planning to use your library to make a website, is it free to use ?
Cheers
Thanks again
Max

2015-07-02 12:17 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by crouti** [comment]
I redownloaded, and now the problem has changed:

dyld: Library not loaded: lib/libopencv_videostab.2.4.dylib

  Referenced from:
/Users/maxunger/Downloads/face_morpher-master/facemorpher/bin/stasm_util

2015-07-02 12:17 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
Its free to use but I'll appreciate a link to this repo if you decide to use it :)

It seems these errors are due to some openCV configurations and not related to face_morpher. This guys seems to have faced this issue with dyld: http://asmaloney.com/2013/01/code/compiling-opencv-on-mac-os-x-10-6/ and more answers on SO.

**Comment by crouti** [comment]
Thank you very much. Sorry to disturb you...
Then another problem:

Traceback (most recent call last):

  File "facemorpher/morpher.py", line 145, in <module>

    args['--alpha'], args['--plot'])

  File "facemorpher/morpher.py", line 133, in morpher

    width, height, num_frames, fps, out_frames, out_video, alpha, plot)

  File "facemorpher/morpher.py", line 109, in morph

    src_face = warper.warp_image(src_img, src_points, points, size)

  File
"/Users/maxunger/Downloads/face_morpher-master/facemorpher/warper.py", line
87, in warp_image

    delaunay.simplices, src_points, dest_points)))

AttributeError: 'Delaunay' object has no attribute 'simplices'
Seems it is an old lib included...
Ever had this problem ?


cheers


2015-07-02 17:30 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
You're using an old version of Scipy. Delaunay.simplices is the new function: http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html

It needs at least > Scipy v0.12.0. The latest version is scipy 0.15.1

**Comment by crouti** [comment]
Thanks a lot for you help. It seems the problem still there:

MacBook-Pro-de-Stephanie:face_morpher-master maxunger$ pip show scipy

---

Metadata-Version: 2.0

Name: scipy

Version: 0.15.1

Summary: SciPy: Scientific Library for Python

Home-page: http://www.scipy.org

Author: SciPy Developers

Author-email: scipy-dev@scipy.org

License: BSD

Location: /Library/Python/2.7/site-packages

Requires:

MacBook-Pro-de-Stephanie:face_morpher-master maxunger$ python
facemorpher/morpher.py --src=max.png --dest=steph.png

max.png

steph.png

Traceback (most recent call last):

  File "facemorpher/morpher.py", line 145, in <module>

    args['--alpha'], args['--plot'])

  File "facemorpher/morpher.py", line 133, in morpher

    width, height, num_frames, fps, out_frames, out_video, alpha, plot)

  File "facemorpher/morpher.py", line 109, in morph

    src_face = warper.warp_image(src_img, src_points, points, size)

  File
"/Users/maxunger/Downloads/face_morpher-master/facemorpher/warper.py", line
87, in warp_image

    delaunay.simplices, src_points, dest_points)))

AttributeError: 'Delaunay' object has no attribute 'simplices'

Is there a path to set anywhere ?

Thanks!
Max


2015-07-02 17:43 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
Can you verify that thats the scipy version being used?

 $: python
 >>> import scipy
 >>> scipy.__version__
 '0.15.1'

**Comment by crouti** [comment]
By the way, of course you'll have a link to your repo it the site comes up!
:)

2015-07-02 17:37 GMT+02:00 Max UNGER <max.unger@termel.fr>:

**Comment by crouti** [comment]
I outputed scipy version in your script, and you are right, the old one
show 0.11.0

2015-07-02 18:37 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by crouti** [comment]
how can i tell python to use the last version ?

2015-07-02 18:37 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
You can delete the old scipy and check that the new scipy is within the pythonpath: <http://stackoverflow.com/questions/20762667/python-doesnt-use-updated-pip-scipy-package>

**Comment by crouti** [comment]
great, you saved me !
Now i launch the same command:

python facemorpher/morpher.py --src=max.png --dest=steph.png

No error output, but nothing happens...

2015-07-02 18:55 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by crouti** [comment]
Do i need images of the exact same dimensions ?

2015-07-02 18:55 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
Add --plot. More command line options in the readme

**Comment by crouti** [comment]
Great !!!!! works
Sorry for disturbing yo all day.
Thanks a lot for your help.
Will keep you posted
Cheers from Paris

2015-07-02 19:16 GMT+02:00 Alyssa Quek <notifications@github.com>:

**Comment by alyssaq** [comment]
Glad we got it working within half a day. I look forward to seeing your website :)

**Comment by alyssaq** [comment]
Enjoy face morpher!

**Comment by crouti** [comment]
Thank you very much,
Cheers
