### ISSUE TITLE
Docker image to try out library

### ISSUE THREAD

**Issue by mochki** [alyssaq/face_morpher#40]
So I made a docker image [here](https://hub.docker.com/r/mohonrid/face-morpher/) albeit with some extra stuff but it's ready to use the face-morpher library. (by way of the command line)

I just know I had the hardest time getting this running and docker ended up saving me. I also see everyone's issues they have getting running that I totally feel for. This kind of works as a guide and a sample.

Anyways, it's an option, I thought I'd pitch in but I'm not sure where I'd put it? 
Also, I wouldn't be offended if y'all hated this and want to destroy this issue into oblivion

**Comment by alyssaq** [comment]
Hi! I use docker to test out on linux too and think its a great idea. face morpher does work on python3.6 and I usually use the image [https://hub.docker.com/r/jjanzic/docker-python3-opencv/](jjanzic/docker-python3-opencv) which has python3.6 + opencv 3.4.1:

$ docker run -v  /Users/alyssa/Desktop/images:/images --name py3 --rm -it jjanzic/docker-python3-opencv bash
root@0dad0912ebbe:/# pip install facemorpher
