### ISSUE TITLE
Possible to produce averaged result that is not en-face?

### ISSUE THREAD

**Issue by solipsy** [alyssaq/face_morpher#42]
If I had images in semi-profile, would it be possible that the averager result be in semi-profile, too? I see the warper submodule could be possibly used for that, bu I'm not sure how. Thanks!

**Comment by alyssaq** [comment]
Im not sure what you mean by semi-profile. You could try it out by passing the folder of images to `averager`. It will automatically ignore images that do not have a face present.

**Comment by solipsy** [comment]
I mean not looking directly at the camera. It seems the more faces there are looking in various directions relative to the camera, the more they are averaged so that the face is on the plane perpendicular to the camera-face line.
For the moment I solved this by generating permutations of the source image list, and then producing an average for each permutation. Some come out as desired.
But just for the sake of asking, is it possible in any way  to arrange the resulting average to be turned away from camera for a specified angle?

**Comment by solipsy** [comment]
Actually, the dest_filename option fixed it, as the result is warped to conform to destination image.

**Comment by alyssaq** [comment]
Fantastic! Im glad the `dest_filename` fixed it.
